[package]
name = "ish"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
thiserror = "2.0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.45"
comfy-table = "7.2.2"
dotenvy = "0.15"
quote = "1.0.46"
proc-macro2 = "1.0.106"
tokio = { version = "1.52.4", features = ["full"] }
futures = "0.3.32"
async-recursion = "1.1.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[[bin]]
name = "ish"
path = "src/main.rs"

[[bin]]
name = "setfont"
path = "src/bin/setfont.rs"
